check_reg_exp = "(Россия|Russia|Российская Федерация|Russian Federation)"

[scheduler]
spy_check_interval = 300 # 5 minutes in secs
east_offfset = 18000 # 5 hours in secs
daily_check_time = "22:00"

[yes]
giphy_query = "yes"
parts = [
    ["А", "Тем временем", "Теперь", "Теперь мой дед говорит, что"],
    ["Spotify"],
    ["наконец вышел в Росcии!", "доступен в России!", "радует россиян своим появлением!", "делает жизнь российский пользователей счастливее!"],
]

[no]
giphy_query = "no"
parts = [
    [
        "А",
        "В это время",
        "В то время как",
        "В данный момент",
        "Тем временем",
        "Спасибо прадеду за деда! Ведь именно дед мне поведал, что",
        "Сижу на удаленке, а тем временем",
        "Это конечно всё очень важно, но",
        "Я в своем познании настолько преисполнился, а в это время",
        "Меня трудно найти, легко потерять и невозможно забыть, ну а",
        "А я люблю дождь, в нем можно спрятать свои слёзы, ведь",
        "Никому не интересны эти новости, голова занята мыслями о том, что",
        "Жили-были дед да бабка. Больше всего на свете они любили говорить о том, что",
        "Цыганка гадала по ладони, сказала, что всё плохо, ведь",
        "Якубович попросил крутить барабан. Я мне надоело его уже крутить. Просто сообщаю, что",
        "Однажды ты спросишь меня, что я люблю больше: тебя или жизнь? А я просто отвечу:",
        "Во сне и на яву, не забывай братву свою. Не знаю, к чему это было, но знаю, что",
        "Прервали мысленный эксперимент Spotify Russia Шрёдингера и выяснили, что",
        "С пацанами совсем забыли, что такое музыка, ведь",
        "Каждый думает, что знает меня, но не каждый знает, что не знает, кто думает. Я точно знаю лишь одно -",
        "Время не лечит, оно просто меняет мысли. Но одна мысль в наших головах остается -",
        "Если тебя предали один раз - то это только первый раз. Но если тебя предали ещё - это уже второй раз. Ну а",
        "Хотел что-то сюда написать, но позабыл. Поэтому коротко:",
        "Какая-то бессмысленная шумиха вокруг этих поправок. Всех должно волновать, только то, что",
        "Как говорил мой дядя:",
        "Пацаны заставляют меня придумывать все эти фразы. Короче,",
        "Вот и помер дед Максим, да и",
        "Запомните! Работа не волк, работа - ворк! Ну а",
    ],
    ["Spotify"],
    [
        "не вышел в России.",
        "остается недоступным.",
        "не вышел.",
        "недоступен в России.",
        "вышел, но не в России.",
        "доступен только в мечтах российских пользователей.",
        "своей недоступностью заставляет грустить пользователей в России.",
        "вышел, но только в параллельной вселенной.",
        "такой недоступный для россиян."
    ],
    [
        "Мы продолжаем следить за ситуацией.",
        "Будем держать вас в курсе.",
        "Продолжаем наблюдение.",
        "Мы ни на секунду не прекращаем наблюдение.",
        "Мы, не отвлекаясь, будем следить за ситуацией.",
        "Ждём и следим вместе с вами.",
        "Сквозь слёзы продолжаем наблюдение.",
        "Запасаемся носовыми платками и ждем вместе с вами, друзья.",
        "Слезы текут, мы не сдаемся.",
        "Забыли обо всём на свете, просто сидим и следим за ситуацией.",
        "Молимся вместе с вами.",
        "Нельзя просто так взять и выпустить Spotify в России.",
        "Кофе, сигареты и мысли о нём (о Spotify).",
        "Keep calm and wait for Spotify.",
        "Попросил у доктора рецепт на антидепрессанты для всех нас.",
        "Учёные всего мира изучают эту проблему, а мы просто ждём."
    ],
]
